# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: docs publish

on:
  push:
    branches: [ develop ]

jobs:
  publishDocs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodule: true
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          version: 14
      # 生成静态文件
      - name: Build
        run: |
          npm install yarn -g
          yarn
          yarn build
      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
      - name: DeployToMain
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /nginx/html
          # 涉及偏安全隐私的信息，不要明文暴露在此文件中，因为repo很可能是公开的，会被所有人看见
          # ${{ ... }} 会应用你在对应项目设置中，配置的对应serets的键值信息，从而保护私密信息不被看到
          host: ${{ secrets.HOST }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PEM }}
